(()=>{
  const root=typeof window!=="undefined"?window:globalThis;
  function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
  function lerp(a,b,t){return a+(b-a)*clamp(t,0,1);}
  function createDuelCamera(){
    const state={centerX:500,zoom:1,shakeX:0,shakeY:0,shakePower:0,zoomKick:0,lastRound:0};
    function reset(arena){state.centerX=Number(arena?.width||1000)/2;state.zoom=1;state.shakeX=0;state.shakeY=0;state.shakePower=0;state.zoomKick=0;state.lastRound=0;}
    function consume(events){for(const event of events||[]){if(event.type==="hit"){const base=event.critical?5.2:Math.min(3.8,1.2+Number(event.amount||0)*.045);state.shakePower=Math.max(state.shakePower,base);state.zoomKick=Math.max(state.zoomKick,event.critical?.035:.018);}else if(event.type==="area"){state.shakePower=Math.max(state.shakePower,3.2);state.zoomKick=Math.max(state.zoomKick,.025);}else if(event.type==="cast")state.zoomKick=Math.max(state.zoomKick,.012);else if(event.type==="ko"){state.shakePower=Math.max(state.shakePower,5.5);state.zoomKick=Math.max(state.zoomKick,.04);}else if(event.type==="phase_change"){state.shakePower=Math.max(state.shakePower,event.phase==="TỬ CHIẾN"?4.2:2.6);state.zoomKick=Math.max(state.zoomKick,event.phase==="TỬ CHIẾN"?.035:.018);}}}
    function update(match,dt,width,height){const arena=match?.arena;if(!arena)return null;const round=match.currentRound,p=round?.fighters?.player,o=round?.fighters?.opponent;if(round?.number&&state.lastRound!==round.number){state.lastRound=round.number;state.centerX=arena.width/2;state.zoom=1;state.shakePower=0;state.zoomKick=0;}const mobile=width<620,baseScale=Math.min(width/arena.width,height/arena.height),distance=p&&o?Math.abs(p.x-o.x):arena.width*.55,focusWidth=clamp(distance+(mobile?410:330),mobile?780:650,arena.width),desiredZoom=clamp(arena.width/focusWidth,1,mobile?1.10:1.24),targetCenter=p&&o?(p.x+o.x)/2:arena.width/2,smooth=1-Math.exp(-Math.max(0,dt)*5.5);state.zoom=lerp(state.zoom,desiredZoom,smooth);const visibleWidth=width/(baseScale*state.zoom),half=Math.min(arena.width/2,visibleWidth/2),boundedCenter=clamp(targetCenter,half,arena.width-half);state.centerX=lerp(state.centerX,boundedCenter,smooth);state.shakePower*=Math.exp(-Math.max(0,dt)*10);state.zoomKick*=Math.exp(-Math.max(0,dt)*8);const shakeScale=mobile?.55:1,t=Number(round?.time||0);state.shakeX=Math.sin(t*53.7)*state.shakePower*shakeScale;state.shakeY=Math.cos(t*47.3)*state.shakePower*.55*shakeScale;const zoom=state.zoom*(1+state.zoomKick*(mobile?.65:1)),scale=baseScale*zoom,worldVisibleWidth=width/scale,boundedHalf=Math.min(arena.width/2,worldVisibleWidth/2),cx=clamp(state.centerX,boundedHalf,arena.width-boundedHalf),ox=width/2-cx*scale+state.shakeX,oy=height-arena.height*scale+state.shakeY;return{scale,ox,oy,centerX:cx,zoom,baseScale,width,height,mobile,shakeX:state.shakeX,shakeY:state.shakeY,x:v=>ox+v*scale,y:v=>oy+v*scale};}
    function layerTransform(camera,arena,parallax=1){if(!camera)return null;const arenaCenter=arena.width/2,layerCenter=arenaCenter+(camera.centerX-arenaCenter)*Number(parallax||0),ox=camera.width/2-layerCenter*camera.scale+camera.shakeX;return{...camera,ox,centerX:layerCenter,x:v=>ox+v*camera.scale,y:v=>camera.oy+v*camera.scale};}
    function getState(){return{...state};}
    return{reset,consume,update,layerTransform,getState};
  }
  root.createDuelCamera=createDuelCamera;
})();