(()=>{
  const root=typeof window!=="undefined"?window:globalThis;
  const FAMILIES=Object.freeze(["physical","projectile","fire","frost","lightning","poison","blood","defense","heal","control","summon","area","chain","time","soul"]);
  const OWNED_TYPES=new Set(["hit","attack_melee","projectile_spawn","cast","status","heal","shield_gain","area","orbit_hit","dodge","revive","ko"]);
  function text(event){return[event?.type,event?.source,event?.skill,event?.status,event?.variant,event?.element].filter(Boolean).join(" ").toLowerCase();}
  function family(event){if(!event||typeof event!=="object")return null;const mapped=typeof root.getDuelVisualProfileForEventV3==="function"?root.getDuelVisualProfileForEventV3(event):null;if(mapped?.primary&&FAMILIES.includes(mapped.primary))return mapped.primary;const t=text(event);if(/lightning|thunder|electric|storm/.test(t))return"lightning";if(/frost|ice|freeze|cold|shatter/.test(t))return"frost";if(/fire|burn|flame|ember|inferno/.test(t))return"fire";if(/poison|venom|toxin|toxic|acid/.test(t))return"poison";if(/blood|lifesteal|vamp|hemorrhage/.test(t))return"blood";if(event.type==="shield_gain"||/shield|barrier|guard|armor|block|aegis/.test(t))return"defense";if(event.type==="heal"||event.type==="revive"||/heal|recover|regen|restore|mend/.test(t))return"heal";if(event.type==="dodge"||/stun|slow|bind|control|root|silence|snare|lock/.test(t))return"control";if(/time|rewind|causal|afterimage|echo/.test(t))return"time";if(event.type==="ko"||/soul|deathmark|death/.test(t))return"soul";if(event.type==="orbit_hit"||/summon|orbit|totem|wisp/.test(t))return"summon";if(/chain|ricochet/.test(t))return"chain";if(event.type==="area"||/explosion|burst|nova|mine|shock/.test(t))return"area";if(event.type==="projectile_spawn")return"projectile";if(event.type==="attack_melee"||event.type==="hit")return"physical";if(event.type==="cast")return"projectile";return null;}
  function createDuelVfxV3({quality="balanced",reducedMotion=false}={}){
    const effects=[];let serial=0,dropped=0,peak=0;
    const profile=quality==="full"?{limit:112,particles:6,alpha:1}:quality==="low"?{limit:36,particles:2,alpha:.62}:{limit:72,particles:4,alpha:.82};
    function ownsEvent(event){return OWNED_TYPES.has(event?.type)&&Boolean(family(event));}
    function lifetime(f,type){if(type==="projectile_spawn")return reducedMotion?.12:.20;if(f==="lightning")return .24;if(f==="physical")return .28;if(f==="chain")return .34;if(f==="fire"||f==="frost")return .46;if(f==="poison"||f==="blood"||f==="control")return .54;if(f==="defense"||f==="summon"||f==="area")return .58;if(f==="heal")return .62;if(f==="time"||f==="soul")return .66;return .35;}
    function consume(events){for(const e of events||[]){if(!ownsEvent(e))continue;const f=family(e),life=lifetime(f,e.type);effects.push({...e,family:f,life,maxLife:life,serial:serial++});}peak=Math.max(peak,effects.length);if(effects.length>profile.limit){const n=effects.length-profile.limit;effects.splice(0,n);dropped+=n;}}
    function update(dt){const d=Math.max(0,Number(dt)||0);for(const e of effects)e.life-=d;for(let i=effects.length-1;i>=0;i--)if(effects[i].life<=0)effects.splice(i,1);}
    function fighter(round,side){return side&&round?.fighters?.[side]||null;}
    function point(e,round,getAnchor){if(Number.isFinite(e.x)&&Number.isFinite(e.y))return{x:e.x,y:e.y};const f=fighter(round,e.target||e.side||e.attacker);if(f&&getAnchor)return getAnchor(f,e.type==="projectile_spawn"?"rightHand":"chest");return{x:500,y:300};}
    function origin(e,round,getAnchor){const f=fighter(round,e.attacker||e.side);return f&&getAnchor?getAnchor(f,"rightHand"):point(e,round,getAnchor);}
    function palette(f){return{physical:[245,245,240],projectile:[205,225,255],fire:[255,125,55],frost:[150,220,255],lightning:[225,235,255],poison:[115,220,130],blood:[245,90,115],defense:[105,205,255],heal:[115,245,175],control:[190,170,255],summon:[245,210,105],area:[205,150,255],chain:[235,155,245],time:[135,225,230],soul:[185,125,235]}[f]||[240,240,240];}
    function rgba(rgb,a){return`rgba(${rgb[0]},${rgb[1]},${rgb[2]},${a})`;}
    function burst(ctx,x,y,s,a,e,rgb){ctx.strokeStyle=rgba(rgb,a);ctx.lineWidth=Math.max(1,2.2*s);ctx.lineCap="round";const n=profile.particles;for(let i=0;i<n;i++){const angle=e.serial*.71+i*Math.PI*2/n,r=(10+(1-a)*18+i*1.5)*s;ctx.beginPath();ctx.moveTo(x+Math.cos(angle)*r*.25,y+Math.sin(angle)*r*.25);ctx.lineTo(x+Math.cos(angle)*r,y+Math.sin(angle)*r);ctx.stroke();}}
    function ring(ctx,x,y,s,a,rgb,base=20){ctx.strokeStyle=rgba(rgb,a);ctx.lineWidth=Math.max(1,2*s);ctx.beginPath();ctx.arc(x,y,(base+(1-a)*18)*s,0,Math.PI*2);ctx.stroke();}
    function beam(ctx,x,y,ox,oy,s,a,rgb,e){ctx.strokeStyle=rgba(rgb,a);ctx.lineWidth=Math.max(1.2,2.4*s);ctx.beginPath();ctx.moveTo(ox,oy);for(let i=1;i<=4;i++){const t=i/4,j=i===4?0:Math.sin(e.serial*3+i*7)*5*s;ctx.lineTo(ox+(x-ox)*t,oy+(y-oy)*t+j);}ctx.stroke();}
    function impactRing(ctx,x,y,s,a,rgb,critical=false){const p=1-a,r=(critical?17:13)+(critical?30:22)*p;ctx.strokeStyle=rgba(rgb,a*(critical?1:.84));ctx.lineWidth=Math.max(1,(critical?3:2)*s);ctx.beginPath();ctx.arc(x,y,r*s,0,Math.PI*2);ctx.stroke();if(!reducedMotion&&critical){ctx.globalAlpha=.38*a;ctx.beginPath();ctx.arc(x,y,(r+8)*s,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;}}
    function slashTrail(ctx,x,y,ox,oy,s,a,rgb,e){const dx=x-ox,dy=y-oy,len=Math.hypot(dx,dy)||1,nx=dx/len,ny=dy/len,px=-ny,py=nx,span=(reducedMotion?18:28)*s,back=(reducedMotion?7:13)*s;ctx.strokeStyle=rgba(rgb,a*.92);ctx.lineWidth=Math.max(1.2,2.8*s);ctx.beginPath();ctx.moveTo(x-nx*back-px*span*.52,y-ny*back-py*span*.52);ctx.quadraticCurveTo(x+nx*4*s,y+ny*4*s,x-nx*back+px*span*.52,y-ny*back+py*span*.52);ctx.stroke();if(!reducedMotion){ctx.strokeStyle=rgba(rgb,a*.32);ctx.lineWidth=Math.max(1,1.2*s);ctx.beginPath();ctx.moveTo(x-nx*(back+10*s)-px*span*.34,y-ny*(back+10*s)-py*span*.34);ctx.lineTo(x-nx*2*s+px*span*.34,y-ny*2*s+py*span*.34);ctx.stroke();}}
    function koBurst(ctx,x,y,s,a,rgb,e){const p=1-a,r=(26+p*62)*s;ctx.strokeStyle=rgba(rgb,a*.88);ctx.lineWidth=Math.max(1.6,3*s);ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke();ctx.strokeStyle=rgba([245,245,240],a*.62);ctx.lineWidth=Math.max(1,1.8*s);const rays=reducedMotion?4:8;for(let i=0;i<rays;i++){const angle=e.serial*.37+i*Math.PI*2/rays,inner=r*.38,outer=r*(.74+p*.22);ctx.beginPath();ctx.moveTo(x+Math.cos(angle)*inner,y+Math.sin(angle)*inner);ctx.lineTo(x+Math.cos(angle)*outer,y+Math.sin(angle)*outer);ctx.stroke();}}
    function render(ctx,tr,match,getAnchor){const round=match?.currentRound;if(!ctx||!tr||!round)return;for(const e of effects){const a=Math.max(0,Math.min(1,e.life/e.maxLife))*profile.alpha,p=point(e,round,getAnchor),o=origin(e,round,getAnchor),x=tr.x(p.x),y=tr.y(p.y),ox=tr.x(o.x),oy=tr.y(o.y),s=tr.scale,rgb=palette(e.family);ctx.save();ctx.globalCompositeOperation=e.family==="poison"||e.family==="blood"?"source-over":"screen";ctx.globalAlpha=1;if(e.family==="projectile"||e.family==="lightning"||e.family==="chain")beam(ctx,x,y,ox,oy,s,a,rgb,e);else if(e.family==="defense"||e.family==="heal"||e.family==="control"||e.family==="summon"||e.family==="area"||e.family==="time"||e.family==="soul")ring(ctx,x,y,s,a,rgb,e.family==="area"?32:22);else burst(ctx,x,y,s,a,e,rgb);if(e.type==="attack_melee")slashTrail(ctx,x,y,ox,oy,s,a,rgb,e);if(e.type==="hit"){impactRing(ctx,x,y,s,a,rgb,Boolean(e.critical));if(e.family==="physical")slashTrail(ctx,x,y,ox,oy,s,a,rgb,e);}if(e.type==="ko")koBurst(ctx,x,y,s,a,rgb,e);if(e.type==="hit"&&Number(e.amount)>0){ctx.globalCompositeOperation="source-over";ctx.globalAlpha=Math.min(1,a+.15);ctx.fillStyle=e.critical?"#fde68a":"#fff";ctx.font=`700 ${Math.max(11,13*s)}px system-ui`;ctx.textAlign="center";ctx.fillText(`${e.critical?"✦ ":""}${Math.max(1,Math.round(e.amount))}`,x,y-24*s-(1-a)*10*s);}ctx.restore();}}
    function getStatus(){const families={};for(const e of effects)families[e.family]=(families[e.family]||0)+1;return{active:effects.length,families,quality,limit:profile.limit,dropped,peak,reducedMotion,combatPolish:"b12a"};}
    return{consume,update,render,getStatus,ownsEvent,effects,familyForEvent:family};
  }
  root.DUEL_VFX_V3_FAMILIES=FAMILIES;root.getDuelVfxV3Family=family;root.createDuelVfxV3=createDuelVfxV3;
})();